branches:
  only:
  - master

language: node_js
sudo: false
node_js:
  - '6'

install:
  - npm install

script:
  - npm run coverage
  - npm install -g ftp-server-for-docker
  - ftp-server-for-docker --help

after_script:
  - npm install codecov && codecov
